# Generated by Django 4.2.1 on 2023-05-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=64)),
                ('destination', models.CharField(max_length=64)),
                ('duration', models.IntegerField()),
                ('departure_date', models.DateField()),
                ('arrival_date', models.DateField()),
                ('airline', models.CharField(max_length=64)),
                ('flight_number', models.CharField(max_length=64)),
                ('seats_available', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
