# Generated by Django 4.2.1 on 2023-05-29 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0006_remove_flight_arrival_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='flight_number',
        ),
    ]
